### PR TITLE
Inline color mode switcher code to reduce flashing

### PR DESCRIPTION
**Pull request by ColdHeat**
Inline the color mode switcher code to reduce flashing. In my testing even with speed throttling there is no flashing of the incorrect color. 

cc @erdnaxe

### CODE REVIEW

**Comment by ColdHeat** [comment]
I think inlining is the right move here, I only caught this issue when putting this code up on demo.ctfd.io as locally the flash doesn't happen at all.

**Comment by ColdHeat** [comment]
I found that the flashing happened on demo.ctfd.io even after this because of Cloudflare's Rocket Loader. However I did notice the flashing locally which this PR did fix so it was still useful.

**Comment by erdnaxe** [comment]
From my testing on Firefox, the color theme shouldn't flash as the browser waits for the JS (as it is in <head>, without defer, so blocking the HTML renderer).

What browser are you using and how are you refreshing the webpage? Are you forcing the browser to flush its cache when testing?

I'm not a fan of inlining JS in HTML as I am used to blocking inline JS in [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), but if that reduces flashing, then why not.

**Comment by ColdHeat** [comment]
@erdnaxe I was testing in a recent version of Chrome. I tried full cache load and a regular refresh. It would even show up when just clicking to other pages. I'm not a big fan of inlining it either but the flash was getting a little annoying.

I think the main cause was Cloudflare's Rocket Loader but I will take a look and try to put it back in a dedicated file. 

One possible cause that I didn't investigate too much was whether the type being module caused Chrome to ignore the defer=False.

**Comment by ColdHeat** [comment]
@erdnaxe I reverted this back to the color_mode_switcher.js file on https://demo.ctfd.io/ and I am seeing a quick flash of white on Chrome and Firefox.

**Comment by erdnaxe** [comment]
@ColdHeat arg, I found the culprit! [`type=module` implies `defer`](https://gist.github.com/jakub-g/385ee6b41085303a53ad92c7c8afd7a6#typemodule-vs-non-module-typetextjavascript-vs-script-nomodule).

So the fix should be as simple as patching CTFd to remove module type on this JS file:
```diff
-<script type="module" src="[/themes/core-beta/static/assets/color_mode_switcher.52334129.js](view-source:https://demo.ctfd.io/themes/core-beta/static/assets/color_mode_switcher.52334129.js)"></script>
+<script src="[/themes/core-beta/static/assets/color_mode_switcher.52334129.js](view-source:https://demo.ctfd.io/themes/core-beta/static/assets/color_mode_switcher.52334129.js)"></script>
```

**Comment by erdnaxe** [comment]
I am going to make a pull request to remove type=module when defer is False in https://github.com/CTFd/CTFd/blob/master/CTFd/constants/assets.py#L28

**Comment by ColdHeat** [comment]
Yeah I do see that removing type="module" makes the original code work. I will go through it that new PR and probably revert the inlining commit.

**Pull request merged**
