### PR TITLE
fix: broken attachment download link

### PR DESCRIPTION
**Pull request by frankli0324**

### CODE REVIEW

**Comment by ColdHeat** [comment]
I haven't tested this out yet but what's the issue with this?

**Comment by frankli0324** [comment]
```jinja
{% for file in files %}
    {% set file = segments | last %}
    <a ... href="{{ file }}" ... />
...
```

**Comment by frankli0324** [comment]
any concerns?

**Comment by MilyMilo** [comment]
@frankli0324 Is right, with the current implementation the download link for attachments is broken.

image

And this throws a 404 when trying to download the attachments, whereas it should serve the file with the proper path:

This is what the link looks after the patch (as it should):
image

Good catch, this looks good to me! 
@ColdHeat

**Comment by MilyMilo** [comment]
If you could just run `yarn format` so prettier is satisfied, as it looks like there are some leftover formatting issues

**Comment by ColdHeat** [comment]
I was just about to format it but thanks for doing that!

**Pull request merged**
